### ISSUE TITLE
Extension Error

### ISSUE THREAD

**Issue by christianboyle** [20chan/github-now#2]
Your instructions seem clear enough and npm builds the extension, but when I drop my `/dist` into `chrome://extensions` I get an error: 

![2020-07-16_09-38-54PM](https://user-images.githubusercontent.com/1605754/87742799-1a231d80-c7ad-11ea-953c-816852f32bba.png)

It seems to be complaining about this line:

![2020-07-16_09-39-53PM](https://user-images.githubusercontent.com/1605754/87742809-2018fe80-c7ad-11ea-8eda-ca909d981c3e.png)

But that doesn't make sense to me, since the `json` response it's processing has the correct encoding `"encoding": "base64"`: https://api.github.com/repos/christianboyle/christianboyle/contents/README.Template.md

Any idea what might be up?

**Comment by 20chan** [comment]
I think that error is not about encoding stuffs. Your profile page has template file named `README.Template.md`, but it requires `README.template.md`, the lowercase `template`.
I'll update Readme, it's my mistake.

By the way, escaping decoded base64 are needed when contents contains unicode characters - check [this answer in stackoverflow](https://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte).

**Comment by christianboyle** [comment]
Ah, yes that fixed it. Thanks for the quick reply and cool app!
